spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studychang  # MySQL 데이터베이스 URL
    username: root  # MySQL 사용자 이름
    password: 1234  # MySQL 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # JPA DDL 자동 업데이트 설정
    show-sql: true  # SQL 쿼리 출력 여부
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL 방언

  servlet:
    multipart:
      enabled: true  # multipart/form-data 요청 활성화
      max-file-size: 10MB  # 업로드할 파일의 최대 크기
      max-request-size: 10MB  # 전체 요청의 최대 크기

